# 잡담 소재를 담은 딕셔너리 생성
topics = [
            {"index": i + 1, "kor": kor, "eng": eng} for i, (kor, eng) in enumerate([
                ("가장 좋아하는 과목", "Favorite subject"),
                ("주말 계획", "Weekend plans"),
                ("좋아하는 영화", "Favorite movie"),
                ("최근 본 드라마", "Recently watched drama"),
                ("좋아하는 책", "Favorite book"),
                ("가족 이야기", "Family stories"),
                ("반려동물 이야기", "Pet stories"),
                ("최근 간 맛집", "Recent visit to a restaurant"),
                ("가고 싶은 여행지", "Dream travel destination"),
                ("최근 관심 있는 취미", "Recent hobby interests"),
                ("친구들과의 추억", "Memories with friends"),
                ("좋아하는 음악 장르", "Favorite music genre"),
                ("어릴 적 꿈", "Childhood dream"),
                ("좋아하는 스포츠", "Favorite sport"),
                ("학교 행사", "School event"),
                ("방과 후 활동", "After school activities"),
                ("최근 본 유튜브 영상", "Recently watched YouTube video"),
                ("좋아하는 게임", "Favorite game"),
                ("최근 들은 웃긴 이야기", "Recently heard funny story"),
                ("가장 기억에 남는 생일", "Most memorable birthday"),
                ("좋아하는 계절", "Favorite season"),
                ("가장 좋아하는 음식", "Favorite food"),
                ("싫어하는 음식", "Least favorite food"),
                ("최근 본 뉴스", "Recent news"),
                ("학교에서 일어난 재미있는 일", "Fun incident at school"),
                ("가장 좋아하는 색", "Favorite color"),
                ("최근 배운 새로운 단어", "Recently learned new word"),
                ("좋아하는 명언", "Favorite quote"),
                ("이상형", "Ideal type"),
                ("좋아하는 패션 스타일", "Favorite fashion style"),
                ("다녀온 여행지", "Places visited"),
                ("꿈꾸는 미래 직업", "Dream future job"),
                ("취미 생활", "Hobbies"),
                ("좋아하는 TV 프로그램", "Favorite TV show"),
                ("어릴 적 기억", "Childhood memory"),
                ("가장 좋아하는 공휴일", "Favorite holiday"),
                ("가장 힘들었던 시험", "Toughest exam"),
                ("최근 구매한 물건", "Recent purchase"),
                ("새로운 기술 배운 것", "Newly learned skill"),
                ("관심 있는 사회 이슈", "Social issues of interest"),
                ("학교에서의 역할", "Role at school"),
                ("가장 친한 친구", "Best friend"),
                ("좋아하는 과자", "Favorite snack"),
                ("싫어하는 과목", "Least favorite subject"),
                ("새로운 친구 사귄 이야기", "Story of making a new friend"),
                ("가장 존경하는 인물", "Most respected person"),
                ("좋아하는 유튜버", "Favorite YouTuber"),
                ("자주 사용하는 앱", "Frequently used app"),
                ("좋아하는 꽃", "Favorite flower"),
                ("재미있게 본 만화책", "Favorite comic book"),
                ("학교에서의 하루 일과", "Daily routine at school"),
                ("최근 들은 노래", "Recently heard song"),
                ("기억에 남는 축제", "Memorable festival"),
                ("좋아하는 아이돌", "Favorite idol"),
                ("나만의 스트레스 해소법", "Personal stress relief methods"),
                ("좋아하는 향수", "Favorite perfume"),
                ("최근 읽은 기사", "Recently read article"),
                ("이상적인 데이트", "Ideal date"),
                ("자주 가는 카페", "Frequently visited café"),
                ("가장 좋아하는 숫자", "Favorite number"),
                ("학교 점심 메뉴", "School lunch menu"),
                ("좋아하는 운동 선수", "Favorite athlete"),
                ("최근 경험한 해프닝", "Recent happening"),
                ("나만의 공부 비법", "Personal study tips"),
                ("가장 기억에 남는 선물", "Most memorable gift"),
                ("좋아하는 음료", "Favorite drink"),
                ("최근 본 공연", "Recently watched performance"),
                ("버킷리스트", "Bucket list"),
                ("재미있게 본 영화 대사", "Favorite movie quote"),
                ("좋아하는 디저트", "Favorite dessert"),
                ("새로운 친구 사귄 이야기", "Making new friends"),
                ("아침에 일어나는 시간", "Wake-up time in the morning"),
                ("최근 본 다큐멘터리", "Recently watched documentary"),
                ("부모님과의 이야기", "Stories with parents"),
                ("학교 생활에서의 목표", "School life goals"),
                ("최근 본 전시회", "Recently attended exhibition"),
                ("좋아하는 TV 예능", "Favorite TV show"),
                ("학교에서의 역할 모델", "Role model at school"),
                ("좋아하는 일러스트레이터", "Favorite illustrator"),
                ("최근 느낀 감정", "Recent feelings"),
                ("좋아하는 여행 방식", "Preferred way to travel"),
                ("자주 쓰는 공부 도구", "Frequently used study tool"),
                ("재미있게 본 광고", "Favorite commercial"),
                ("최근 했던 봉사활동", "Recent volunteer activity"),
                ("가장 좋아하는 커피 종류", "Favorite type of coffee"),
                ("학교 도서관에서 읽은 책", "Book read in the school library"),
                ("학교 생활의 즐거움", "Joys of school life"),
                ("가장 좋아하는 휴대폰 기능", "Favorite phone feature"),
                ("최근 발견한 맛집", "Recently discovered restaurant"),
                ("가장 좋아하는 말", "Favorite saying"),
                ("최근 본 뮤지컬", "Recently watched musical"),
                ("좋아하는 사진작가", "Favorite photographer"),
                ("최근 다녀온 박물관", "Recently visited museum"),
                ("학교에서의 친구 관계", "Friendships at school"),
                ("좋아하는 미술 작품", "Favorite artwork"),
                ("최근 본 웹툰", "Recently read webtoon"),
                ("학교에서의 장난", "School pranks"),
                ("가장 좋아하는 초콜릿 종류", "Favorite type of chocolate"),
                ("나만의 비밀 공간", "Personal secret place"),
                ("최근 참여한 동아리 활동", "Recent club activities"),
                ("시험 기간 스트레스 해소법", "Stress relief during exam period"),
                ("친구들과의 쇼핑 경험", "Shopping experience with friends"),
                ("좋아하는 메이크업 브랜드", "Favorite makeup brand"),
                ("최근 산 화장품", "Recently bought cosmetics"),
                ("학교 축제 준비 이야기", "Preparing for a school festival"),
                ("좋아하는 패션 트렌드", "Favorite fashion trend"),
                ("인스타그램에서 본 재미있는 것", "Interesting things seen on Instagram"),
                ("관심 있는 뷰티 유튜버", "Beauty YouTubers of interest"),
                ("다이어트 팁", "Diet tips"),
                ("가장 좋아하는 케이팝 그룹", "Favorite K-pop group"),
                ("좋아하는 연예인", "Favorite celebrity"),
                ("최근 본 로맨틱 코미디 영화", "Recently watched romantic comedy movie"),
                ("인스타그램 피드 꾸미기 팁", "Tips for decorating Instagram feed"),
                ("친구들과의 수다 주제", "Topics for chatting with friends"),
                ("생일 파티 준비", "Birthday party preparation"),
                ("좋아하는 향수 브랜드", "Favorite perfume brand"),
                ("SNS에서 본 재미있는 밈", "Funny memes seen on SNS"),
                ("좋아하는 스타일의 가방", "Favorite bag style"),
                ("최근 본 패션쇼", "Recently watched fashion show"),
                ("헤어 스타일 변화 이야기", "Hair style change story"),
                ("좋아하는 네일아트 디자인", "Favorite nail art design"),
                ("최근 간 카페 추천", "Recent café recommendation"),
                ("인스타그램 스토리 꾸미기", "Decorating Instagram stories"),
                ("좋아하는 액세서리", "Favorite accessories"),
                ("친구들과의 사진 촬영 팁", "Photo shooting tips with friends"),
                ("좋아하는 아이돌의 최신 소식", "Latest news about favorite idol"),
                ("좋아하는 드라마 커플", "Favorite drama couple"),
                ("친구들과의 피크닉", "Picnic with friends"),
                ("주말 브런치 추천 메뉴", "Weekend brunch recommendations"),
                ("다이어리 꾸미기 아이디어", "Ideas for decorating a diary"),
                ("최근 읽은 로맨스 소설", "Recently read romance novel"),
                ("학교에서의 패션 고민", "Fashion concerns at school"),
                ("친구들과의 댄스 챌린지", "Dance challenge with friends"),
                ("좋아하는 아이스크림 맛", "Favorite ice cream flavor"),
                ("SNS에서 본 유머 글", "Funny posts seen on SNS"),
                ("좋아하는 마스카라 브랜드", "Favorite mascara brand"),
                ("친구들과의 놀이 공원 방문기", "Visit to an amusement park with friends"),
                ("주말 영화 추천", "Weekend movie recommendations"),
                ("좋아하는 쿠션 팩트", "Favorite cushion foundation"),
                ("최근 본 패션 블로거", "Recently watched fashion blogger"),
                ("친구들과의 새로운 도전", "New challenges with friends"),
                ("좋아하는 립스틱 색상", "Favorite lipstick color"),
                ("좋아하는 향기 나는 로션", "Favorite scented lotion"),
                ("최근 본 웹 드라마", "Recently watched web drama"),
                ("친구들과의 뮤직비디오 촬영", "Shooting a music video with friends"),
                ("좋아하는 패션 악세사리", "Favorite fashion accessories"),
                ("최근 본 SNS 챌린지", "Recently seen SNS challenge"),
                ("친구들과의 사진 촬영 팁", "Photo shooting tips with friends"),
                ("좋아하는 네일 아트", "Favorite nail art"),
                ("최근 본 인플루언서 추천템", "Recently seen influencer-recommended items"),
                ("친구들과의 파자마 파티", "Pajama party with friends"),
                ("좋아하는 샴푸 브랜드", "Favorite shampoo brand"),
                ("최근 본 패션 아이템", "Recently seen fashion item"),
                ("좋아하는 스타일의 청바지", "Favorite style of jeans"),
                ("최근 본 로맨스 웹툰", "Recently read romance webtoon"),
                ("친구들과의 여행 사진", "Travel photos with friends"),
                ("좋아하는 뷰티 제품", "Favorite beauty products"),
                ("최근 본 로맨틱 영화 명장면", "Recently watched romantic movie scene"),
                ("친구들과의 요가 클래스", "Yoga class with friends"),
                ("좋아하는 로맨틱 소설", "Favorite romantic novel"),
                ("최근 본 유명 인플루언서", "Recently watched famous influencer"),
                ("친구들과의 캠핑", "Camping with friends"),
                ("좋아하는 샤워젤", "Favorite shower gel"),
                ("최근 본 패션 아이템 리뷰", "Recently watched fashion item review"),
                ("친구들과의 책 읽기 모임", "Book club with friends"),
                ("좋아하는 스타일의 원피스", "Favorite dress style"),
                ("최근 본 SNS 스토리", "Recently seen SNS story"),
                ("친구들과의 디저트 만들기", "Making desserts with friends"),
                ("좋아하는 향기 나는 스프레이", "Favorite scented spray"),
                ("최근 본 뷰티 트렌드", "Recently seen beauty trend"),
                ("친구들과의 축제 준비", "Preparing for a festival with friends"),
                ("좋아하는 여름 패션", "Favorite summer fashion"),
                ("최근 본 인스타그램 필터", "Recently seen Instagram filter"),
                ("친구들과의 헤어스타일 변화", "Hair style change with friends"),
                ("좋아하는 플랫슈즈", "Favorite flats"),
                ("최근 본 로맨틱 드라마", "Recently watched romantic drama"),
                ("친구들과의 쇼핑몰 탐방", "Exploring the mall with friends"),
                ("좋아하는 선글라스 브랜드", "Favorite sunglasses brand"),
                ("최근 본 연애 상담 글", "Recently seen dating advice post"),
                ("친구들과의 사진 촬영 팁", "Photo shooting tips with friends"),
                ("좋아하는 스타일의 모자", "Favorite hat style"),
                ("최근 본 SNS 패션 피드", "Recently seen SNS fashion feed"),
                ("친구들과의 바닷가 여행", "Beach trip with friends"),
                ("좋아하는 귀걸이 디자인", "Favorite earring design"),
                ("최근 본 드라마 명대사", "Recently seen drama quotes"),
                ("친구들과의 스노우보드 여행", "Snowboarding trip with friends"),
                ("좋아하는 핸드폰 케이스 디자인", "Favorite phone case design"),
                ("최근 본 패션 위크 하이라이트", "Recently watched fashion week highlights"),
                ("친구들과의 봄 소풍", "Spring picnic with friends"),
                ("좋아하는 액세서리 스타일", "Favorite accessory style"),
                ("최근 본 유명 셀럽 패션", "Recently seen celebrity fashion"),
                ("친구들과의 여름 캠프", "Summer camp with friends"),
                ("좋아하는 아로마 오일", "Favorite aroma oil"),
                ("최근 본 드라마 엔딩", "Recently seen drama ending"),
                ("친구들과의 스키 여행", "Ski trip with friends"),
                ("좋아하는 겨울 패션 아이템", "Favorite winter fashion item"),
                ("최근 본 인스타그램 라이브", "Recently watched Instagram live"),
                ("친구들과의 DIY 액세서리 만들기", "DIY accessory making with friends"),
                ("좋아하는 향수 조합", "Favorite perfume combination"),
                ("최근 본 로맨틱 소설 리뷰", "Recently read romantic novel review"),
                ("친구들과의 SNS 챌린지 참여", "Participating in SNS challenges with friends"),
                ("좋아하는 뷰티 브랜드", "Favorite beauty brand"),
                ("최근 본 패션 아이템 추천", "Recently seen fashion item recommendations"),
                ("친구들과의 비치 파티", "Beach party with friends"),
                ("좋아하는 스카프 스타일", "Favorite scarf style"),
                ("최근 본 인플루언서 패션 리뷰", "Recently watched influencer fashion review"),
                ("친구들과의 헤어 컬러 변화", "Hair color change with friends"),
                ("좋아하는 바디미스트 향기", "Favorite body mist scent"),
                ("최근 본 드라마 커플", "Recently seen drama couple"),
                ("친구들과의 스파 데이", "Spa day with friends"),
                ("좋아하는 뷰티 꿀팁", "Favorite beauty tips"),
                ("최근 본 로맨스 영화 예고편", "Recently watched romance movie trailer"),
                ("친구들과의 스토리 촬영", "Story filming with friends"),
                ("좋아하는 로맨틱 코미디", "Favorite romantic comedy"),
                ("최근 본 SNS 패션 트렌드", "Recently seen SNS fashion trend"),
                ("친구들과의 메이크업 도전", "Makeup challenge with friends"),
                ("좋아하는 뷰티 아이템", "Favorite beauty item"),
                ("최근 본 패션 이벤트", "Recently attended fashion event"),
                ("친구들과의 힐링 타임", "Healing time with friends"),
                ("좋아하는 스타일의 팔찌", "Favorite bracelet style"),
                ("최근 본 유명 셀럽 인터뷰", "Recently watched celebrity interview"),
                ("친구들과의 자전거 타기", "Biking with friends"),
                ("좋아하는 패션 잡지", "Favorite fashion magazine"),
                ("최근 본 로맨스 웹툰 리뷰", "Recently read romance webtoon review"),
                ("친구들과의 여름 바캉스", "Summer vacation with friends"),
                ("좋아하는 향기 나는 바디로션", "Favorite scented body lotion"),
                ("최근 본 뷰티 꿀팁", "Recently seen beauty tips"),
                ("친구들과의 일상 브이로그", "Daily vlogs with friends"),
                ("좋아하는 스타일의 귀걸이", "Favorite earring style"),
                ("최근 본 SNS 챌린지", "Recently seen SNS challenge"),
                ("친구들과의 여름 해변 여행", "Summer beach trip with friends"),
                ("좋아하는 패션 블로거", "Favorite fashion blogger"),
                ("최근 본 로맨스 소설 추천", "Recently read romance novel recommendation"),
                ("친구들과의 핸드메이드 액세서리", "Handmade accessories with friends"),
                ("좋아하는 스타일의 신발", "Favorite shoe style")
            ])
        ]